### ISSUE TITLE
azkaban can not work. requests.packages.urllib3 does not exist

### ISSUE THREAD

**Issue by Codefor** [mtth/azkaban#23]
```
Traceback (most recent call last):
  File "/usr/local/bin/azkaban", line 9, in <module>
    load_entry_point('azkaban==0.9.5', 'console_scripts', 'azkaban')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.7/dist-packages/azkaban/__main__.py", line 98, in <module>
    from azkaban.project import Project
  File "/usr/local/lib/python2.7/dist-packages/azkaban/project.py", line 8, in <module>
    from .util import AzkabanError, Adapter, flatten, temppath, write_properties
  File "/usr/local/lib/python2.7/dist-packages/azkaban/util.py", line 13, in <module>
    from requests.packages.urllib3 import disable_warnings
ImportError: No module named packages.urllib3
```

**Comment by mtth** [comment]
My guess is you have a module named `requests` that overrides the original one (either in your current directory or in your `PYTHONPATH`). Do you have a file named `requests.py` or a folder named `requests`?

**Comment by mtth** [comment]
I'm assuming you were able to address this, feel free to reopen if not.
