### ISSUE TITLE
AttributeError: 'AzkabanError' object has no attribute 'message'

### ISSUE THREAD

**Issue by juhoautio** [mtth/azkaban#29]
To enable integration tests I created `~/.azkabanrc` with 

```
[azkaban]
test.alias = local

[alias.local]
url = http://localhost:8081
```

Then I ran

```
nosetests
```

There was an error:
```
..............................................Azkaban password for JuhoAutio@http://localhost:8081:
Azkaban password for JuhoAutio@http://localhost:8081: Azkaban password for JuhoAutio@http://localhost:8081: E
======================================================================
ERROR: test_remote.TestCreateDelete.test_create_delete_project
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/JuhoAutio/.pyenv/versions/3.7.0/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/Users/JuhoAutio/ideaprojects/AzkabanCli/azkaban/test/test_remote.py", line 97, in test_create_delete_project
    ok_(not self.project_exists(self.project))
  File "/Users/JuhoAutio/ideaprojects/AzkabanCli/azkaban/test/test_remote.py", line 90, in project_exists
    self.session.upload_project(project, path)
  File "/Users/JuhoAutio/ideaprojects/AzkabanCli/azkaban/azkaban/remote.py", line 651, in upload_project
    self._refresh() # ensure that the ID is valid
  File "/Users/JuhoAutio/ideaprojects/AzkabanCli/azkaban/azkaban/remote.py", line 765, in _refresh
    if not 'Incorrect Login.' in err.message:
AttributeError: 'AzkabanError' object has no attribute 'message'
```

Hmm not sure if I can reproduce this test run consistently.. but any way it shows the error `AttributeError: 'AzkabanError' object has no attribute 'message'` which is real. I believe since python 2.6 or something `Exception` doesn't have `message` any more.

----

Apart from that, how can I successfully run the integration tests?

I set the url with credentials:
```
[alias.local]
url = azkaban:azkaban@http://localhost:8081
```
After this I `nosetests` were run through, but there were quite many errors. For example:

> AssertionError: 'Execution queued successfully wi' != 'Execution submitted successfully'

**Comment by mtth** [comment]
Fixed in https://github.com/mtth/azkaban/pull/32, thanks @juhoautio!
