### ISSUE TITLE
Error when creating a new project on deploy in Azkaban 3.59.0 

### ISSUE THREAD

**Issue by Ralnoc** [mtth/azkaban#33]
We are currently running Azkaban 3.1.0 in our production environment and all aspects of this code works great on 3.1.0.

However we are in the process of getting 3.59.0 working in our lab, in preparation of upgrading to a more current version. Almost everything works, however we have one issue that we have discovered.

**Issue**
* We execute the following to build and upload a project: `azkaban build -cp project.py -a lab-azkaban`
* When a Project does exist in Azkaban, the build and upload works without issue.
* When the project does not exist in Azkaban, get this error after we enter the password and press enter to upload the project:

```
Azkaban password for username@http://azkaban.example.com:
Traceback (most recent call last):
  File "/path/to/virtualenvs/venv_name/lib/python2.7/site-packages/azkaban/util.py", line 310, in wrapper
    return func(*args, **kwargs)
  File "/path/to/virtualenvs/venv_name/lib/python2.7/site-packages/azkaban/__main__.py", line 502, in main
    ['ZIP', '--url', '--alias', '--replace', '--create', '--option']
  File "/path/to/virtualenvs/venv_name/lib/python2.7/site-packages/azkaban/__main__.py", line 460, in build_project
    res = _upload_zip(session, project.name, _zip, _create, archive_name)
  File "/path/to/virtualenvs/venv_namelib/python2.7/site-packages/azkaban/__main__.py", line 320, in _upload_zip
    callback=_callback,
  File "/path/to/virtualenvs/venv_name/lib/python2.7/site-packages/azkaban/remote.py", line 673, in upload_project
    data=form,
  File "/path/to/virtualenvs/venv_name/lib/python2.7/site-packages/azkaban/remote.py", line 902, in _request
    raise err
HTTPError: 410 Client Error: Gone for url: http://azkaban.example.com/manager
```

This error only manifests when we have the `-c` argument being passed and the project does not already exist. If the project already exists, then the build and upload works without issue.

Are there any recommendations regarding where this issue might be arising? I was hoping you might have some insight.

Thank you.

**Comment by mtth** [comment]
Fixed in https://github.com/mtth/azkaban/pull/34 - thanks again for the PR @Ralnoc!
